blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
# post views
    #path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    #path('<int:id>/', views.post_detail, name='post_detail'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',views.post_share, name='post_share'),
    path('<int:post_id>/comment/',views.post_comment, name='post_comment'),
]

mysite2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .filter(status=Post.Status.PUBLISHED)

class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,
    on_delete=models.CASCADE,
    related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    photo = models.ImageField(upload_to='post_images/%Y/%m/%d',blank=True)
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.

    class Meta:
        ordering = ['-publish']
        indexes = [
                    models.Index(fields=['-publish']),]
     
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                            self.publish.month,
                                            self.publish.day,
                                            self.slug])
    
class Comment(models.Model):
    post = models.ForeignKey(Post,
    on_delete=models.CASCADE,
    related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)
    

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage,\
PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

from django.views.generic import ListView

from django.views.decorators.http import require_POST


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a Comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to the database
        comment.save()
    return render(request, 'blog/post/comment.html',
                            {'post': post,
                            'form': form,
                            'comment': comment})


class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    

# def post_list(request):
#     post_list = Post.published.all()
#     # Pagination with 3 posts per page
#     paginator = Paginator(post_list, 3)
#     page_number = request.GET.get('page')
#     try:
#          posts = paginator.page(page_number)
#     except PageNotAnInteger:
#     # If page_number is not an integer deliver the first page
#         posts = paginator.page(1)
#     except EmptyPage:
#     # If page_number is out of range deliver last page of results
#         posts = paginator.page(paginator.num_pages)
#     return render(request,'blog/post/list.html',{'posts': posts})





def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()
    return render(request,'blog/post/detail.html',{'post': post,'comments': comments,'form': form})

'''
def post_detail(request, id):
    try:
        post = Post.published.get(id=id)
    except Post.DoesNotExist:
        raise Http404("No Post found.")
    return rensder(request,'blog/Post/detail.html',{'post': post})'''

'''def post_detail(request, id):
    post = get_object_or_404(Post,id=id,status=Post.Status.PUBLISHED)
    return render(request,'blog/Post/detail.html',{'post': post})

'''


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                    [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                        'form': form,
                        'sent': sent})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "css/coin-slider.css" %}" />
<script type="text/javascript" src="{% static "js/cufon-yui.js" %}"></script>
<script type="text/javascript" src="{% static "js/cufon-aller-700.js" %}"></script>
<script type="text/javascript" src="{% static "js/jquery-1.4.2.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/script.js" %}"></script>
<script type="text/javascript" src="{% static "js/coin-slider.min.js" %}"></script>
</head>
<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="searchform">
        <form id="formsearch" name="formsearch" method="post" action="#">
          <span>
            <input name="editbox_search" class="editbox_search" id="editbox_search" maxlength="80" value="Search our ste:" type="text" />
          </span>
          <input name="button_search" src="{% static "images/search.gif" %}" class="button_search" type="image" />
        </form>
      </div>
      <div class="logo">
        <h1><a><span>Blog</span> <small>Company Slogan Here</small></a></h1>
      </div>
      <div class="clr"></div>
      <div class="menu_nav">
        <ul>
          <li class="active"><a href="#"><span>Home Page</span></a></li>
          <li><a href="#"><span>Admin</span></a></li>
        </ul>
      </div>
      <div class="clr"></div>
      <div class="slider">
        <div id="coin-slider">
          {% block imgs %}
          {% for post in posts %}
          
          <a href="#"><img src="{{ post.photo.url }}" width="960" height="360" alt="" /><span><big>{{ post.title }}</big><br />
                 {{ post.body|truncatewords:70 }}</span>
          {% endfor %}
          {% endblock %}
        </div>
        <div class="clr"></div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
        {% block content %}{% endblock %}
        {% block pagination %}{% endblock %}
      </div>
    </div>
  </div>
</div>
</body>
</html>

blog/templates/blog/base1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
<div id="content">
{% block content %}
{% endblock %}
</div>
<div id="sidebar">
<h2>My blog</h2>
<p>This is my blog</p>
</div>
</body>
</html>

blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}
{% block title %}Add a comment{% endblock %}
{% block content %}
{% if comment %}
<h2>Your comment has been added.</h2>
<p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
{% else %}
{% include "blog/post/includes/comment_form.html" %}
{% endif %}
{% endblock %}

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% block title %}{{ post.title }}{% endblock %}
{% block imgs %}
<a href="#"><img src="{{ post.photo.url }}" width="960" height="360" alt="" />
{% endblock %}
{% block content %}
<div class="article">
    <h2><span>{{ post.title }}</span></h2>
    <div class="clr"></div>
    <p>Posted by <a>{{ post.author }}</a> <span>&nbsp;&bull;&nbsp;</span></p>
    <p>{{ post.body|linebreaks }} </p>
    <p><a href="#"></a> <span>&nbsp;&bull;&nbsp;</span> {{ post.publish }} <span>&nbsp;&bull;&nbsp;</span></p>
  </div>
<p><a href="{% url "blog:post_share" post.id %}">Share this post</a></p>
    {% with comments.count as total_comments %}
<h2>
{{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}
{% for comment in comments %}
<div class="comment"> <a href="#"><img src="{% static "images/userpic.gif" %}" width="40" height="40" alt="" class="userpic" /></a>
    <p><a href="#">{{ comment.name }}</a> Says:<br />
        {{ comment.created }}</p>
    <p>{{ comment.body|linebreaks }}</p>
  </div>
{% empty %}
<p>There are no comments.</p>
{% endfor %}
<div class="article">
    <h2><span>Leave a</span> comment</h2>
    <div class="clr"></div>
    <form action="{% url "blog:post_comment" post.id %}" method="post" id="leavereply">
        {% csrf_token %}
      <ol>
        <li>
          <label for="name">Name (required)</label>
          <input id="name" name="name" class="text" />
        </li>
        <li>
          <label for="email">Email Address (required)</label>
          <input id="email" name="email" class="text" />
        </li>

        <li>
          <label for="message">Your Message</label>
          <textarea id="message" name="body" rows="8" cols="50"></textarea>
        </li>
        <li>
          <input  type="submit" value="Add comment" class="send" />
          <div class="clr"></div>
        </li>
      </ol>
    </form>
  </div>
{% endblock %}

blog/templates/blog/post/includes/comment_form.html
<h2>Add a new comment</h2>
<form action="{% url "blog:post_comment" post.id %}" method="post">
{{ form.as_p }}
{% csrf_token %}
<p><input type="submit" value="Add comment"></p>
</form>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}

{% block content %}
{% for post in posts %}
        <div class="article">
            <h2>{{ post.title }}</h2>
            <p class="infopost">Posted <span class="date">on {{ post.publish }}</span> by <a>{{ post.author }}</a> &nbsp;&nbsp;|&nbsp;&nbsp; <a href="{{ post.get_absolute_url }}" class="com">Comments <span>{{ post.comments.count }}</span></a></p>
          <div class="clr"></div>
            <div class="img"><img src="{{ post.photo.url}}" width="198" height="208" alt="" class="fl" /></div>
                <div class="post_content">
                    {{ post.body|truncatewords:70 }}
            <p class="spec"><a href="{{ post.get_absolute_url }}" class="rm">Read more</a></p>
          </div>
          <div class="clr"></div>
        </div>
{% endfor %}
{% endblock %}

{% block pagination %}
{% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form method="post">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        <p class="pages">
            <small>Page {{ page.number }} of {{ page.paginator.num_pages }}</small>
    {% if page.has_previous %}
    <a href="?page=1">&laquo;</a>
    <a href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a>
    {% endif %}
        <span>{{ page.number }}</span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a>
    <a href="?page={{ page.paginator.num_pages }}"> &raquo;</a>
    {% endif %}
        </p>
    </span>
    </div>


    
    {% comment %}

        <p class="pages">
            <small>Page {{ page.number }} of {{ page.paginator.num_pages }}</small>
    {% if page.has_previous %}
    <a href="?page=1">&raquo;</a>
    <a href="?page={{ page.previous_page_number }}">{{ page.number - 1 }}</a>
    {% endif %}
        <span>{{ page.number }}</span>
    {% if page.has_next %}
    <a href="?page={{ page_obj.paginator.num_pages }}"> &laquo;</a>
    {% endif %}
        </p>

        <p class="pages"><small>Page 1 of 2</small> <span>1</span> <a href="#">2</a> <a href="#">&raquo;</a></p>
     {% endcomment %}